name: GenerateProtoWorkflow
on:
  repository_dispatch:
    types: [ProtoFileChanges]
jobs:
  protoGenJobs:
    runs-on: [ubuntu-latest]
    permissions: 
      contents: read
      packages: write
    steps:
      - name: ListenChanges
        run: |
          echo commit message: ${{ github.event.client_payload.message }}.
      - uses: actions/checkout@v2
      - name: Set git global config
        run: |
          git config --global user.name "Tarsidi"
          git config --global user.email "tarsidi.danesh@tiket.com"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        env:
          GITHUB_USERNAME: 'tarsidi-danesh'
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: mvn --settings settings.xml --file pom.xml deploy
