name: GenerateProtoWorkflow
on:
  repository_dispatch:
    types: [ProtoFileChanges]
jobs:
  protoGenJobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: ListenChanges
        run: |
          echo commit message: ${{ github.event.client_payload.message }}.
