name: GenerateProtoWorkflow
on:
  repository_dispatch:
    types: [ProtoFileChanges]
jobs:
  build:
    runs-on: [ubuntu-latest]
    permissions: 
      contents: read
      packages: write
    steps:
      - name: Changes Log
        run: |
          echo commit message: ${{ github.event.client_payload.message }}.
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Set git global config
        run: |
          git config --global user.name "Tarsidi"
          git config --global user.email "tarsidi.danesh@tiket.com"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Update version
        env:
          GITHUB_USERNAME: 'tarsidi-danesh'
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: mvn --file pom.xml versions:set -DnewVersion=${{ github.event.client_payload.version }}
      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Tarsidi
          author_email: tarsidi.danesh@tiket.com
          message: 'Update version'
          add: 'pom.xml'
      - name: Deploy to Github Package Registry
        env:
          GITHUB_USERNAME: 'tarsidi-danesh'
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: mvn --settings settings.xml --file pom.xml deploy
