name: GenerateProtoWorkflow
on:
  repository_dispatch:
    types: [ProtoFileChanges]
jobs:
  protoGenJobs:
    runs-on: [ubuntu-latest]
    steps:
      - name: ListenChanges
        run: |
          echo commit message: ${{ github.event.client_payload.message }}.
      - uses: actions/checkout@v2
      - name: Set git global config
        run: |
          git config --global user.name "Tarsidi"
          git config --global user.email "tarsidi.danesh@tiket.com"
          git config --global user.password "${{ secrets.REPO_ACCESS_TOKEN }}"
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean install release:clean release:prepare release:perform
